### ISSUE TITLE
UE 5.1 not compiling

### ISSUE THREAD

**Issue by thomasvanta** [backspacetokyo/UE-NDIMedia#2]
Getting this errors when trying to compile in UE 5.1

/Plugins/NDIMedia/Source/NDIMedia/Public/NDIMediaCapture.h:32:15: Declaration of 'CaptureSceneViewportImpl' overrides a 'final' function

/Plugins/NDIMedia/Source/NDIMedia/Public/NDIMediaCapture.h:33:15: Declaration of 'CaptureRenderTargetImpl' overrides a 'final' function

it looks like something has changed in 5.1 for the media engine

Any clue?

**Comment by satoruhiga** [comment]
I have not tested with 5.1 yet, I will update when release version is available.

**Comment by thomasvanta** [comment]
Looks like some functions have been deprecated.

This seems to work:

```
 virtual bool InitializeCapture() override;
virtual bool PostInitializeCaptureViewport(TSharedPtr<FSceneViewport>& InSceneViewport) override;
virtual bool PostInitializeCaptureRenderTarget(UTextureRenderTarget2D* InRenderTarget) override;

//virtual bool CaptureSceneViewportImpl(TSharedPtr<FSceneViewport>& InSceneViewport) override;
//virtual bool CaptureRenderTargetImpl(UTextureRenderTarget2D* InRenderTarget) override;
	
```
